use std::{mem::offset_of, any::Any, option::Option, sync::Arc};
use tokio::sync::Mutex;

use glacier_reflect::{
    member::MemberInfoFlags,
    type_info::{
        ClassInfoData, ValueTypeInfoData, FieldInfoData, TypeInfo, TypeInfoData, TypeObject, TypeFunctions,
    }, type_registry::TypeRegistry,
};

pub mod a_i_tools;
pub mod achievements;
pub mod ant;
pub mod app;
pub mod audio;
pub mod audio_core_voice_monitor_shared;
pub mod auto_players;
pub mod battle_a_i;
pub mod battle_a_i_shared;
pub mod bifrost;
pub mod cloth;
pub mod cloth_base;
pub mod core;
pub mod creature_loco;
pub mod creature_loco_shared;
pub mod debris;
pub mod decal;
pub mod decal_base;
pub mod decal_volume_base;
pub mod decal_volume_render;
pub mod decal_volume_sim;
pub mod deformation;
pub mod destruction;
pub mod dice_commons;
pub mod dice_commons_shared;
pub mod dice_online_shared;
pub mod dice_shooter;
pub mod dice_shooter_shared;
pub mod dice_svg_rasterizer;
pub mod dice_svg_rasterizer_shared;
pub mod e_a_character_physics;
pub mod e_a_character_physics_shared;
pub mod effect;
pub mod effect_base;
pub mod emitter;
pub mod emitter_base;
pub mod entitlements;
pub mod entity;
pub mod expression;
pub mod first_party_overlay;
pub mod frosted_strings_shared;
pub mod game_base;
pub mod game_client;
pub mod game_client_u_i;
pub mod game_common;
pub mod game_management;
pub mod game_server;
pub mod game_shared;
pub mod game_shared_u_i;
pub mod gameplay_client_server;
pub mod gameplay_sim;
pub mod gameplay_timeline;
pub mod input;
pub mod input_shared;
pub mod l_m_s_billboard;
pub mod l_m_s_cinematic_destruction;
pub mod l_m_s_regular_grid;
pub mod linear_media;
pub mod lua_runner;
pub mod matchmaking;
pub mod memento;
pub mod morph_base;
pub mod morph_sim;
pub mod movie_base;
pub mod movie_entity;
pub mod network;
pub mod nucleus;
pub mod nv_rvm_dx11;
pub mod nv_rvm_dx12;
pub mod online;
pub mod online_shared;
pub mod origin_shared;
pub mod p_a2_client;
pub mod party;
pub mod patch_backend;
pub mod pathfinding;
pub mod pathfinding_shared;
pub mod peer;
pub mod physics;
pub mod pixel_painting_shared;
pub mod quickscope;
pub mod quickscope_shared;
pub mod rail_ride_heli;
pub mod render;
pub mod render_base;
pub mod rt_rvm_dx12;
pub mod rvm_common;
pub mod rvm_dx11_pc;
pub mod rvm_dx12;
pub mod rvm_dx12_pc;
pub mod schematics;
pub mod shadow_extrusion;
pub mod shadow_extrusion_shared;
pub mod snitch;
pub mod snowglobe;
pub mod soldier;
pub mod soldier_shared;
pub mod state_stream;
pub mod statistics;
pub mod streaming_video_player;
pub mod streaming_video_player_shared;
pub mod telemetry;
pub mod telemetry_shared;
pub mod terrain_base;
pub mod terrain_render;
pub mod terrain_sim;
pub mod timeline;
pub mod u_i;
pub mod u_i_incubator;
pub mod u_i_incubator_shared;
pub mod vegetation;
pub mod vehicle;
pub mod vehicle_shared;
pub mod w_s;
pub mod w_s_shared;
pub mod wall_of_doom;
pub mod wall_of_doom_shared;
pub mod water_interact_base;
pub mod water_interact_sim;
pub mod weapon;
pub mod weapon_shared;
pub mod web_browser;
pub mod web_utils;
pub mod wind;
pub mod world_base;
pub mod world_render;
pub mod world_sim;
pub mod zone_streamer;

pub fn register_mod_types(registry: &mut TypeRegistry) {
    a_i_tools::register_a_i_tools_types(registry);
    achievements::register_achievements_types(registry);
    ant::register_ant_types(registry);
    app::register_app_types(registry);
    audio::register_audio_types(registry);
    audio_core_voice_monitor_shared::register_audio_core_voice_monitor_shared_types(registry);
    auto_players::register_auto_players_types(registry);
    battle_a_i::register_battle_a_i_types(registry);
    battle_a_i_shared::register_battle_a_i_shared_types(registry);
    bifrost::register_bifrost_types(registry);
    cloth::register_cloth_types(registry);
    cloth_base::register_cloth_base_types(registry);
    core::register_core_types(registry);
    creature_loco::register_creature_loco_types(registry);
    creature_loco_shared::register_creature_loco_shared_types(registry);
    debris::register_debris_types(registry);
    decal::register_decal_types(registry);
    decal_base::register_decal_base_types(registry);
    decal_volume_base::register_decal_volume_base_types(registry);
    decal_volume_render::register_decal_volume_render_types(registry);
    decal_volume_sim::register_decal_volume_sim_types(registry);
    deformation::register_deformation_types(registry);
    destruction::register_destruction_types(registry);
    dice_commons::register_dice_commons_types(registry);
    dice_commons_shared::register_dice_commons_shared_types(registry);
    dice_online_shared::register_dice_online_shared_types(registry);
    dice_shooter::register_dice_shooter_types(registry);
    dice_shooter_shared::register_dice_shooter_shared_types(registry);
    dice_svg_rasterizer::register_dice_svg_rasterizer_types(registry);
    dice_svg_rasterizer_shared::register_dice_svg_rasterizer_shared_types(registry);
    e_a_character_physics::register_e_a_character_physics_types(registry);
    e_a_character_physics_shared::register_e_a_character_physics_shared_types(registry);
    effect::register_effect_types(registry);
    effect_base::register_effect_base_types(registry);
    emitter::register_emitter_types(registry);
    emitter_base::register_emitter_base_types(registry);
    entitlements::register_entitlements_types(registry);
    entity::register_entity_types(registry);
    expression::register_expression_types(registry);
    first_party_overlay::register_first_party_overlay_types(registry);
    frosted_strings_shared::register_frosted_strings_shared_types(registry);
    game_base::register_game_base_types(registry);
    game_client::register_game_client_types(registry);
    game_client_u_i::register_game_client_u_i_types(registry);
    game_common::register_game_common_types(registry);
    game_management::register_game_management_types(registry);
    game_server::register_game_server_types(registry);
    game_shared::register_game_shared_types(registry);
    game_shared_u_i::register_game_shared_u_i_types(registry);
    gameplay_client_server::register_gameplay_client_server_types(registry);
    gameplay_sim::register_gameplay_sim_types(registry);
    gameplay_timeline::register_gameplay_timeline_types(registry);
    input::register_input_types(registry);
    input_shared::register_input_shared_types(registry);
    l_m_s_billboard::register_l_m_s_billboard_types(registry);
    l_m_s_cinematic_destruction::register_l_m_s_cinematic_destruction_types(registry);
    l_m_s_regular_grid::register_l_m_s_regular_grid_types(registry);
    linear_media::register_linear_media_types(registry);
    lua_runner::register_lua_runner_types(registry);
    matchmaking::register_matchmaking_types(registry);
    memento::register_memento_types(registry);
    morph_base::register_morph_base_types(registry);
    morph_sim::register_morph_sim_types(registry);
    movie_base::register_movie_base_types(registry);
    movie_entity::register_movie_entity_types(registry);
    network::register_network_types(registry);
    nucleus::register_nucleus_types(registry);
    nv_rvm_dx11::register_nv_rvm_dx11_types(registry);
    nv_rvm_dx12::register_nv_rvm_dx12_types(registry);
    online::register_online_types(registry);
    online_shared::register_online_shared_types(registry);
    origin_shared::register_origin_shared_types(registry);
    p_a2_client::register_p_a2_client_types(registry);
    party::register_party_types(registry);
    patch_backend::register_patch_backend_types(registry);
    pathfinding::register_pathfinding_types(registry);
    pathfinding_shared::register_pathfinding_shared_types(registry);
    peer::register_peer_types(registry);
    physics::register_physics_types(registry);
    pixel_painting_shared::register_pixel_painting_shared_types(registry);
    quickscope::register_quickscope_types(registry);
    quickscope_shared::register_quickscope_shared_types(registry);
    rail_ride_heli::register_rail_ride_heli_types(registry);
    render::register_render_types(registry);
    render_base::register_render_base_types(registry);
    rt_rvm_dx12::register_rt_rvm_dx12_types(registry);
    rvm_common::register_rvm_common_types(registry);
    rvm_dx11_pc::register_rvm_dx11_pc_types(registry);
    rvm_dx12::register_rvm_dx12_types(registry);
    rvm_dx12_pc::register_rvm_dx12_pc_types(registry);
    schematics::register_schematics_types(registry);
    shadow_extrusion::register_shadow_extrusion_types(registry);
    shadow_extrusion_shared::register_shadow_extrusion_shared_types(registry);
    snitch::register_snitch_types(registry);
    snowglobe::register_snowglobe_types(registry);
    soldier::register_soldier_types(registry);
    soldier_shared::register_soldier_shared_types(registry);
    state_stream::register_state_stream_types(registry);
    statistics::register_statistics_types(registry);
    streaming_video_player::register_streaming_video_player_types(registry);
    streaming_video_player_shared::register_streaming_video_player_shared_types(registry);
    telemetry::register_telemetry_types(registry);
    telemetry_shared::register_telemetry_shared_types(registry);
    terrain_base::register_terrain_base_types(registry);
    terrain_render::register_terrain_render_types(registry);
    terrain_sim::register_terrain_sim_types(registry);
    timeline::register_timeline_types(registry);
    u_i::register_u_i_types(registry);
    u_i_incubator::register_u_i_incubator_types(registry);
    u_i_incubator_shared::register_u_i_incubator_shared_types(registry);
    vegetation::register_vegetation_types(registry);
    vehicle::register_vehicle_types(registry);
    vehicle_shared::register_vehicle_shared_types(registry);
    w_s::register_w_s_types(registry);
    w_s_shared::register_w_s_shared_types(registry);
    wall_of_doom::register_wall_of_doom_types(registry);
    wall_of_doom_shared::register_wall_of_doom_shared_types(registry);
    water_interact_base::register_water_interact_base_types(registry);
    water_interact_sim::register_water_interact_sim_types(registry);
    weapon::register_weapon_types(registry);
    weapon_shared::register_weapon_shared_types(registry);
    web_browser::register_web_browser_types(registry);
    web_utils::register_web_utils_types(registry);
    wind::register_wind_types(registry);
    world_base::register_world_base_types(registry);
    world_render::register_world_render_types(registry);
    world_sim::register_world_sim_types(registry);
    zone_streamer::register_zone_streamer_types(registry);
}

